AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31
Description: >
  Dynamo stream to Lambda

Globals:
  Function:
    Timeout: 600
  Api:
    TracingEnabled: true

Resources:

  FunctionDynamoStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
              Resource: "*"
      Events:
        DynamoStream:
          Type: DynamoDB
          Properties:
            Stream: "arn:aws:dynamodb:ap-southeast-1:885537931206:table/posts/stream/2023-07-19T07:38:27.320"
            StartingPosition: LATEST
            BatchSize: 1

Outputs:
  FunctionDynamoStream:
    Description: "FunctionDynamoStream"
    Value: !GetAtt FunctionDynamoStream.Arn
    Export:
      Name: FunctionDynamoStream

