version: 0.2
phases: 

  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - cd aws-lambda-server
      - npm install
      - cd ..
      - cd aws-cognito
      - npm install
      - cd ..
      - cd aws-eventBridge
      - npm install
      - cd ..
      - cd aws-s3
      - npm install
      - cd ..
      - cd aws-sns
      - npm install
      - cd ..
  
  build:
    commands:
      - sam build -t template.yaml
      - sam deploy --stack-name intern-viettel --s3-bucket intern-viettel-storage-bucket --s3-prefix intern-viettel --region ap-southeast-1 --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-confirm-changeset

  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`ExpressApi`].OutputValue' --output text > my-app/.env
      - aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`AuthApi`].OutputValue' --output text >> my-app/.env
      - aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`ImageApi`].OutputValue' --output text >> my-app/.env
      - cd my-app
      - npm install
      - npm run build
      - cd ..
      - aws s3 sync my-app/build s3://intern-viettel-storage-bucket/intern-viettel --delete

artifacts:
  files:
    - '**/*'
  base-directory: 'my-app/build'

