version: 0.2
phases: 

  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - cd aws-lambda-server
      - npm install
      - cd ..
      - cd auth-service
      - npm install
      - cd ..
      - cd notification
      - npm install
      - cd ..
      - cd img-service
      - npm install
      - cd ..
      - cd my-app
      - echo Installing source NPM dependencies...
      - npm install
      
  
  build:
    commands:
      - sam build -t ../template.yaml
      - sam deploy --stack-name intern-viettel --s3-bucket intern-viettel-storage-bucket --s3-prefix intern-viettel --region ap-southeast-1 --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-confirm-changeset
      - REACT_APP_API_LAMBDA=$(aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`ExpressApi`].OutputValue' --output text)
      - echo $REACT_APP_API_LAMBDA
      - echo $REACT_APP_API_LAMBDA >> .env
      - REACT_APP_API_AUTH=$(aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`AuthApi`].OutputValue' --output text)
      - echo $REACT_APP_API_AUTH
      - echo $REACT_APP_API_AUTH >> .env
      - REACT_APP_API_S3=$(aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`ImageApi`].OutputValue' --output text)
      - echo $REACT_APP_API_S3
      - echo $REACT_APP_API_S3 >> .env
      - REACT_APP_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`ClientId`].OutputValue' --output text)
      - echo $REACT_APP_CLIENT_ID
      - echo $REACT_APP_CLIENT_ID >> .env
      - REACT_APP_USERPOOL_ID=$(aws cloudformation describe-stacks --stack-name intern-viettel --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
      - echo $REACT_APP_CLIENT_ID
      - echo $REACT_APP_CLIENT_ID >> .env
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'my-app/build'
