version: 0.2
phases: 

  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd my-app
      - npm install
      - cd ..
      - cd aws-lambda-server
      - npm install
      - cd ..
      - cd aws-cognito
      - npm install
      - cd ..
      - cd aws-eventBridge
      - npm install
      - cd ..

  build:
    commands:
      - sam build -t template.yaml
      - sam deploy --stack-name intern-viettel --s3-bucket $artifact_bucket --s3-prefix intern-viettel --region ap-southeast-1 --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM --no-confirm-changeset
