AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Project intern viettel"

Resources:
  ServerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: aws-lambda-server/server.yaml

  EventBridgeStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: aws-eventBridge/eventBridge.yaml

  CognitoStack: 
    Type: AWS::Serverless::Application
    Properties:
      Location: aws-cognito/cognito.yaml

  StorageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: aws-s3/Storage.yaml
      Parameters:
        TopicNotificationImage: !GetAtt NotificationStack.Outputs.TopicNotificationImage

  NotificationStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: aws-sns/Notification.yaml
      Parameters:
        Api: !GetAtt ServerStack.Outputs.ExpressApi

Outputs:
  ExpressApi:
    Description: "API Gateway endpoint URL for Prod stage for Express server"
    Value: !Sub "https://${ServerStack.Outputs.ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api"

  AuthApi:
    Description: "API Gateway endpoint URL for Prod stage for Auth server"
    Value: !Sub "https://${CognitoStack.Outputs.AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  ImageApi:
    Description: "API Gateway endpoint URL for Prod stage for Image server"
    Value: !Sub "https://${StorageStack.Outputs.ImageApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"