AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Project intern viettel"

Resources:
  ServerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: aws-lambda-server/template.yaml

  NotificationStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: notification/template.yaml

  AuthStack: 
    Type: AWS::Serverless::Application
    Properties:
      Location: auth-service/template.yaml

  ImageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: img-service/template.yaml
  

Outputs:
  ExpressApi:
    Description: "API Gateway endpoint URL for Prod stage for Express server "
    Value: !Sub "${ServerStack.Outputs.ExpressApi}/api"

  AuthApi:
    Description: "API Gateway endpoint URL for Prod stage for Auth server"
    Value: !Sub "${AuthStack.Outputs.AuthApi}"

  ImageApi:
    Description: "API Gateway endpoint URL for Prod stage for Image server"
    Value: !Sub "${ImageStack.Outputs.ImageApi}"

  ClientId: 
    Description: "Client id for Cognito"
    Value: !Sub "${AuthStack.Outputs.ExpressUserPoolClientId}"
  
  UserPoolId: 
    Description: "User pool id for Cognito"
    Value: !Sub "${AuthStack.Outputs.ExpressUserPoolId}"