AWSTemplateFormatVersion: '2010-09-09'
Description: "Project intern viettel"



Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0abcdef1234567890  # Replace with your AMI ID, for example, a suitable Linux AMI
      KeyName: my-key-pair           # Replace with your key pair name
      SecurityGroups:
        - Ref: MySecurityGroup
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: My security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
