AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31
Description: >
  Web Server with AWS Lambda, API Gateway, DynamoDB.

Globals:
  Function:
    Timeout: 600
  Api:
    TracingEnabled: true

Resources:
  # express api rest
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes: ["*/*"]
      # Auth:
      #   DefaultAuthorizer: GeneralAuth
      #   Authorizers:
      #     GeneralAuth:
      #       UserPoolArn: !Ref ExpressUserPool
      #       Identity:
      #         Header: Authorization
      #         ValidationExpression: Bearer.*
      #     CustomLambdaAuthorizer:
      #       FunctionArn: !GetAtt ExpressFunction.Arn
      #       Identity:
      #         Header: Authorization
      #         ValidationExpression: Bearer .*

  # lambda authorizer
  # AuthFunctionPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !GetAtt ExpressFunction.Arn
  #     Action: lambda:InvokeFunction
  #     Principal: cognito-idp.amazonaws.com
  #     SourceArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExpressUserPool}

  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ExpressApi:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /{proxy+}
            Method: ANY
      Role: !GetAtt ExpressFunctionRole.Arn
      Environment:
        Variables:
          JWT_SECRET: "tungjav"

  # role for express api rest
  ExpressFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
        

Outputs:
  ExpressFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt ExpressFunction.Arn

  ExpressApi:
    Description: API Gateway endpoint URL for Prod stage for ExpressApi function
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
