AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31
Description: >
  Web Server with AWS Lambda, API Gateway, DynamoDB.

Globals:
  Function:
    Timeout: 600
  Api:
    TracingEnabled: true

Parameters:
  Api: 
    Type: String
    Description: API Gateway

Resources:

  ModerationFunction: 
    Type: AWS::Serverless::Function
    Properties: 
      Handler: moderation.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRekognitionFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          API: !Ref Api

  TopicNotificationImage:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SNS-Notification-Image
      Subscription:
        - Endpoint: !GetAtt ModerationFunction.Arn
          Protocol: lambda
 
  TopicNotificationImagePolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: SNS-Notification-Image-Policy
        Version: "2012-10-17"
        Statement:
          - Sid: SNS-Notification-Image-Policy
            Effect: Allow
            Principal:
              Service: rekognition.amazonaws.com
            Action: sns:Publish
            Resource: !Ref TopicNotificationImage
      Topics:
        - !Ref TopicNotificationImage
 
  ModerationFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ModerationFunction.Arn
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref TopicNotificationImage

  SNSPlatformSetipFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
      - PolicyName: "SNSPlatformSetipFunctionPolicy"
        PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sns:CreatePlatformApplication"
                  - "sns:CreatePlatformEndpoint"
                  - "sns:DeleteEndpoint"
                  - "sns:DeletePlatformApplication"
                  - "sns:GetEndpointAttributes"
                  - "sns:GetPlatformApplicationAttributes"
                  - "sns:SetEndpointAttributes"
                  - "sns:SetPlatformApplicationAttributes"
                  - "sns:Subscribe"
                  - "sns:Unsubscribe"
                Resource: "*"
                  # - !Ref TopicNotificationImage
                  # - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*
      - PolicyName: LambdaExecution
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"

  SNSPlatformSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: createPlatform.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Role: !GetAtt SNSPlatformSetipFunctionRole.Arn
      Environment:
        Variables:
          API: !Ref Api
          # FCM_API_KEY: '{{resolve:ssm:fcm_api_key_android}}'

  # SNSPlatformApplication: 
  #   Type: Custom::SNSPlatformApplication
  #   Properties:
  #     ServiceToken: !GetAtt SNSPlatformSetupFunction.Arn
  #     Platform: GCM
  #     Name: SNS-Platform-Application
  
  # SNSPlatformSetupFunctionPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !GetAtt SNSPlatformSetupFunction.Arn
  #     Action: lambda:InvokeFunction
  #     Principal: sns.amazonaws.com
  #     SourceArn: !Ref TopicNotificationImage

Outputs:
  TopicNotificationImage:
    Description: "Topic Notification Image"
    Value: !Ref TopicNotificationImage
  # SNSPlatformApplication:
  #   Description: "SNS Platform Application"
  #   Value: !Ref SNSPlatformApplication
  SNSPlatformSetupFunction:
    Description: "SNS Platform Setup Function"
    Value: !Ref SNSPlatformSetupFunction